joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: khop_joint
  pid: {p: 10.0, i: 0.1, d: 10.0}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: khau_2_joint
  pid: {p: 10.0, i: 0.1, d: 10.0}