joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: khop_joint
  pid: {p: 100.0, i: 20.0, d: 30.0}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: khau_2_joint
  pid: {p: 100.0, i: 1.0, d: 10.0}