xe_tang:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10

  banh_4_controller:
    type: effort_controllers/JointVelocityController
    joint: than_xe_banh_4
    pid: {p: 0.01, i: 0.01, d: 0.01}
  banh_2_controller:
    type: effort_controllers/JointVelocityController
    joint: than_xe_banh_2
    pid: {p: 0.01, i: 0.01, d: 0.01}