joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
diff_drive_controller:
    type: diff_drive_controller/DiffDriveController
    left_wheel: banh_xe_4_joint
    right_wheel: banh_xe_2_joint
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    publish_rate: 50
    wheel_separation: 0.135  # Adjust based on your robot
    wheel_radius: 0.05      # Adjust based on your robot
    cmd_vel_timeout: 0.25
    velocity_rolling_window_size: 10