joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

banh_4_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: "left_joint"
  pid: {p: 100.0, i: 0.1, d: 10.0}

banh_2_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: "right_joint"
  pid: {p: 100.0, i: 0.1, d: 10.0}

