xe_tang:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  banh_4_controller:
    type: effort_controllers/JointVelocityController
    joint: than_xe_banh_4
    pid: {p: 100.0, i: 0.01, d: 10.0}
  banh_2_controller:
    type: effort_controllers/JointVelocityController
    joint: than_xe_banh_2
    pid: {p: 100.0, i: 0.01, d: 10.0}