gazebo_ros_control:
  pid_gains:
    banh_xe_1_joint:
      p: 10.0
      i: 0.1
      d: 10.0
    banh_xe_2_joint:
      p: 10.0
      i: 0.1
      d: 10.0
    banh_xe_3_joint:
      p: 10.0
      i: 0.1
      d: 10.0
    banh_xe_4_joint:
      p: 10.0
      i: 0.1
      d: 10.0